
export default `/* Version: 10.3.1.3657.xr */
/* "05-Aug-2020 09:36:50" */

SCHEMA
 user="FLAMBRIGGE" time=1596611920/* "05-Aug-2020 09:18:40" */
{
  VERSION=1253152407/* "17-Sep-2009 03:53:27" */
  MAJOR_VERSION=10
  MINOR_VERSION=3
  MAINTENANCE_VERSION=1
  BUILD_VERSION=3664
  BUILD_ID="xr"
  VERSION_STR="10.3.1.3664.xr"
  ONLINE_UPGRADE=F
}
LOCALE
 user="FLAMBRIGGE" time=1596611920/* "05-Aug-2020 09:18:40" */
{
  LOCALE="English_United States.1252"
}
ENUMERATION_SET NAME="L_NIR_PROD_S1" FIXED=F
 user="RPOLLINGE1" time=1534836702/* "21-Aug-2018 09:31:42" */
{
  DESCRIPTION="NIR Produktauswahl Sonde 1"
  CATEGORY="Named Sets/L_ANL"
  ENTRY VALUE=0 NAME="LEER / AUS" { }
  ENTRY VALUE=1 NAME="Sulfon" { }
  ENTRY VALUE=2 NAME="Iodosulfuron" { }
  ENTRY VALUE=3 NAME="Amidosulfuron" { }
  ENTRY VALUE=4 NAME="Ethoxysulfuron" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="DURCHFL_REG_ZF" FIXED=F
 user="TZENKLUSEN" time=1387267824/* "17-Dec-2013 09:10:24" */
{
  DESCRIPTION="Umschaltung Regelung Zugabe Zentrifuge"
  CATEGORY="Named Sets/L_AP"
  ENTRY VALUE=0 NAME="fixe Regelventilstellung" { }
  ENTRY VALUE=1 NAME="Durchflussregelung" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_AKTO_OPT_AKT" FIXED=F
 user="ADMINISTRATOR" time=1233154954/* "28-Jan-2009 16:02:34" */
{
  DESCRIPTION="GF SET_AKTR FP_OPTION_AKTION  / Version 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="KEINE AKTION" { }
  ENTRY VALUE=1 NAME="VENTIL ZU" { }
  ENTRY VALUE=2 NAME="VENTIL AUF" { }
  ENTRY VALUE=3 NAME="MOTOR AUS" { }
  ENTRY VALUE=4 NAME="MOTOR EIN" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_AKTO_OPT_MOD" FIXED=F
 user="ADMINISTRATOR" time=1233154954/* "28-Jan-2009 16:02:34" */
{
  DESCRIPTION="GF SET_AKTR FP_OPTION_MODE  / Version 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="CAS UND CAS2_FREI EIN" { }
  ENTRY VALUE=1 NAME="CAS UND CAS2_FREI AUS" { }
  ENTRY VALUE=2 NAME="CAS AUT UND CAS2_FREI EIN" { }
  ENTRY VALUE=3 NAME="CAS AUT UND CAS2_FREI AUS" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_AUF_ZU" FIXED=F
 user="ADMINISTRATOR" time=1525171545/* "01-May-2018 12:45:45" */
{
  DESCRIPTION="GF AUSTR_GS / Version 1.0 / 30-Mai-2017 M. Demostene"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="AUF" { }
  ENTRY VALUE=1 NAME="ZU" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_AUSTRAG" FIXED=F
 user="ADMINISTRATOR" time=1233154954/* "28-Jan-2009 16:02:34" */
{
  DESCRIPTION="GF AUSTR_GS Flag ""Austrag Bereit"" / Version 1.0 / 21-Sep-2001 H. Hutter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="nicht Bereit" { }
  ENTRY VALUE=1 NAME="Bereit" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_AUSTR_GS_OPT" FIXED=F
 user="ADMINISTRATOR" time=1247032256/* "08-Jul-2009 07:50:56" */
{
  DESCRIPTION="GF AUSTR_GS FP_OPTION / Version 1.0 / 21-Sep-2001 H. Hutter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="Blasbalken" { }
  ENTRY VALUE=1 NAME="Schaelmesserduese Auto" { }
  ENTRY VALUE=2 NAME="Blasbalken u Schaelmduese Auto" { }
  ENTRY VALUE=3 NAME="Schaelmesser MAN" { }
  ENTRY VALUE=4 NAME="Blasbalken u Schaelmduese MAN" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_BEDING" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF BEDING FP_FSB_VERGLEICH  / Version 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="KLEINER" { }
  ENTRY VALUE=1 NAME="GRÖSSER" { }
  ENTRY VALUE=2 NAME="VERZWEIGUNG" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_BEDING_DI" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF BEDING_DI FP_FSB_VERGLEICH  / Version 1.0 / 06-Apr-2004 R. Andereggen"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="False" { }
  ENTRY VALUE=1 NAME="True" { }
  ENTRY VALUE=2 NAME="Verzweigung" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_BEGAS_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF BEGAS FP_OPTION / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="AUS" { }
  ENTRY VALUE=5 NAME="UEBERLAGERUNG" { }
  ENTRY VALUE=10 NAME="UEBERDRUCK" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_BUCHEN" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF DRUCK & GF VAKPUMPE / Buchen & Freigeben  / Version 1.0 / 17-Feb-2005 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="frei" { }
  ENTRY VALUE=1 NAME="gebucht" { }
  ENTRY VALUE=2 NAME="buchen" { }
  ENTRY VALUE=3 NAME="freigeben" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_DRUCK_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF DRUCK FP_OPTION / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="AUS" { }
  ENTRY VALUE=1 NAME="VAKUUM" { }
  ENTRY VALUE=2 NAME="ABLUFT1_REGLER" { }
  ENTRY VALUE=3 NAME="ABLUFT2_REGLER" { }
  ENTRY VALUE=4 NAME="ABLUFT1_AUF" { }
  ENTRY VALUE=5 NAME="ABLUFT2_AUF" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_DST_MANSTART" FIXED=F
 user="ADMINISTRATOR" time=1525170418/* "01-May-2018 12:26:58" */
{
  DESCRIPTION="GF DESTIL FP_MANSTART / VERSION 1.0 / 20-Feb-2017 M. Demostene"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="NEIN" { }
  ENTRY VALUE=1 NAME="JA" { }
  ENTRY VALUE=2 NAME="JA MIT MAN FSB d Niv EMPF" { }
  ENTRY VALUE=3 NAME="JA MIT MAN FSB d Niv SEND" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_FUEL_SPUE_OP" FIXED=F
 user="ADMINISTRATOR" time=1525169675/* "01-May-2018 12:14:35" */
{
  DESCRIPTION="GF FUELLEN FP_SPUEL_LEER / Version 2.0 / 24-Okt-2014 Ch. Zeiter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="OHNE" { }
  ENTRY VALUE=1 NAME="Spuelen Leerlaufen mit Pumpe" { }
  ENTRY VALUE=2 NAME="Spuelen Leerlaufen ohne Pumpe" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_GAS_MANSTART" FIXED=F
 user="ADMINISTRATOR" time=1525169246/* "01-May-2018 12:07:26" */
{
  DESCRIPTION="GF GAS FP_MANSTART / VERSION 1.0 / 07-Dezember-2012 Ch. Zeiter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="NEIN" { }
  ENTRY VALUE=1 NAME="JA" { }
  ENTRY VALUE=2 NAME="JA MIT MAN FSB FQ" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_GAS_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF GAS FP_FSB_OPTION / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=1 NAME="ZEIT - Reaktionszeit" { }
  ENTRY VALUE=2 NAME="DRUCK - Druck hoch und Reaktionszeit" { }
  ENTRY VALUE=3 NAME="MENGE - Menge und Reaktionszeit" { }
  ENTRY VALUE=4 NAME="DURCHFLUSS - Durchfluss tief und Reaktionszeit" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="LGF_GOP_OPT" FIXED=F
 user="ADMINISTRATOR" time=1247032257/* "08-Jul-2009 07:50:57" */
{
  DESCRIPTION="GF SET_GOP FP_GOP_OPT / Version 1.0 / 26-Sep.-2007 R. Andereggen"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="RESET" { }
  ENTRY VALUE=1 NAME="MAN_SETZEN" { }
  ENTRY VALUE=2 NAME="ZAEHLEN" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_GOP_PARAM" FIXED=F
 user="ADMINISTRATOR" time=1247032257/* "08-Jul-2009 07:50:57" */
{
  DESCRIPTION="GF SET_GOP FP_GOP_PARAM / Version 1.0 / 26-Sep.-2007 R. Andereggen"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="GOP_ZAEHLER" { }
  ENTRY VALUE=1 NAME="GOP_TRANS_01" { }
  ENTRY VALUE=2 NAME="GOP_TRANS_02" { }
  ENTRY VALUE=3 NAME="GOP_TRANS_03" { }
  ENTRY VALUE=4 NAME="GOP_TRANS_04" { }
  ENTRY VALUE=5 NAME="GOP_TRANS_05" { }
  ENTRY VALUE=6 NAME="GOP_TRANS_06" { }
  ENTRY VALUE=7 NAME="GOP_TRANS_07" { }
  ENTRY VALUE=8 NAME="GOP_TRANS_08" { }
  ENTRY VALUE=9 NAME="GOP_TRANS_09" { }
  ENTRY VALUE=10 NAME="GOP_TRANS_10" { }
  ENTRY VALUE=11 NAME="KEINE" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_HK_OBEN_UNTE" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF HK FP_TT_INNEN / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="UNTEN - Temp Transmitter unten" { }
  ENTRY VALUE=1 NAME="OBEN - Temp Transmitter oben" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_HK_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF HK FP_OPTION / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="AUS" { }
  ENTRY VALUE=1 NAME="MANTELTEMP" { }
  ENTRY VALUE=2 NAME="INNENTEMP" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_SCHAELEN_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF SCHAELEN FP_OPTION / Version 1.0 / 21-Sep-2001 H. Hutter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="Manuell" { }
  ENTRY VALUE=1 NAME="Automatisch" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_SR_CAS2_FREI" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF SET_REGL FP_CAS2_FREI / VERSION 1.0 / 08-JUN-2002 H. HUTTER"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="CAS2_FREI EIN" { }
  ENTRY VALUE=1 NAME="CAS2_FREI AUS" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_SR_MODE" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF SET_REGL FP_MODE / VERSION 1.0 / 08-JUN-2002 H. HUTTER"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="NICHT AENDERN" { }
  ENTRY VALUE=1 NAME="CAS" { }
  ENTRY VALUE=2 NAME="ROUT" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_SR_MODE_FREI" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF SET_REGL FP_MODE_FREI / VERSION 1.0 / 08-JUN-2002 H. HUTTER"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="CAS" { }
  ENTRY VALUE=1 NAME="CAS und AUT" { }
  ENTRY VALUE=2 NAME="CAS und AUT und MAN" { }
  ENTRY VALUE=3 NAME="ROUT" { }
  ENTRY VALUE=4 NAME="ROUT und MAN" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_TR_FSB_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF TRANSF FP_FSB_OPTION / VERSION 2.0 / 05-Jun-2002 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=1 NAME="ABSOLUT NIVEAU" { }
  ENTRY VALUE=2 NAME="ENTLEEREN SENDER" { }
  ENTRY VALUE=3 NAME="DELTA NIVEAU" { }
  ENTRY VALUE=4 NAME="MENGE ZAEHLER" { }
  ENTRY VALUE=5 NAME="MAN ENDE" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="LGF_TR_MANSTART" FIXED=F
 user="ADMINISTRATOR" time=1525170818/* "01-May-2018 12:33:38" */
{
  DESCRIPTION="GF TRANSF FP_MANSTART / VERSION 2.0 / 03-April-2012 Ch. Zeiter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="NEIN" { }
  ENTRY VALUE=1 NAME="JA" { }
  ENTRY VALUE=2 NAME="JA MIT MAN FSB" { }
  ENTRY VALUE=3 NAME="JA MIT EXT FSB FQ" { }
  ENTRY VALUE=4 NAME="NEIN MIT EXT FSB FQ" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_TR_PULS_VENTIL" FIXED=F
 user="ADMINISTRATOR" time=1315290629/* "06-Sep-2011 08:30:29" */
{
  DESCRIPTION="GF TRANSF FP_PULS_VENTIL / VERSION 1.0 / 10-Feb-2011 A. Stoffel"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="Kein Ventil" { }
  ENTRY VALUE=1 NAME="EMPF_V_1" { }
  ENTRY VALUE=2 NAME="EMPF_V_2" { }
  ENTRY VALUE=3 NAME="EMPF_V_3" { }
  ENTRY VALUE=4 NAME="SEND_V_1" { }
  ENTRY VALUE=5 NAME="SEND_V_2" { }
  ENTRY VALUE=6 NAME="SEND_V_3" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_TR_REG_STRAT" FIXED=F
 user="ADMINISTRATOR" time=1233154955/* "28-Jan-2009 16:02:35" */
{
  DESCRIPTION="GF TRANSF FP_REGEL_STRAT / VERSION 2.0 / 17-Feb-2005 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="KEINE" { }
  ENTRY VALUE=1 NAME="KAS_EMPF" { }
  ENTRY VALUE=2 NAME="REGLER_EMPF" { }
  ENTRY VALUE=3 NAME="FC_EMPF" { }
  ENTRY VALUE=4 NAME="FC_Z_ST" { }
  ENTRY VALUE=5 NAME="FY_EMPF" { }
  ENTRY VALUE=6 NAME="FY_Z_ST" { }
  ENTRY VALUE=7 NAME="KAS_Z_ST" { }
  ENTRY VALUE=8 NAME="REGLER_Z_ST" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_TR_SPUEL_OPT" FIXED=F
 user="ADMINISTRATOR" time=1525169687/* "01-May-2018 12:14:47" */
{
  DESCRIPTION="GF TRANSF FP_SPUEL_LEER / VERSION 2.0 / 24-Okt-2014 Ch. Zeiter"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="OHNE - ohne Spülen/Leerlaufen" { }
  ENTRY VALUE=1 NAME="SENDER MIT PUMPE - Spülen/Leerlaufen von Sender" { }
  ENTRY VALUE=2 NAME="ZAEHLER_ST - Spülen/Leerlaufen von Zählerstation" { }
  ENTRY VALUE=3 NAME="SENDER OHNE PUMPE - Spülen/Leerlaufen von Sender" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LGF_VAKPUMPE_OPT" FIXED=F
 user="ADMINISTRATOR" time=1233154956/* "28-Jan-2009 16:02:36" */
{
  DESCRIPTION="GF VAKPUMPE FP_OPTION / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=1 NAME="EIN UND FREIGEBEN" { }
  ENTRY VALUE=2 NAME="EIN UND BUCHEN" { }
  ENTRY VALUE=3 NAME="AUS UND FREIGEBEN" { }
  ENTRY VALUE=4 NAME="AUS UND BUCHEN" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="LGF_WEG" FIXED=F
 user="ADMINISTRATOR" time=1233154956/* "28-Jan-2009 16:02:36" */
{
  DESCRIPTION="GF FP_WEG / VERSION 1.0 / 01-Okt-2001 L. Hertli"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=1 NAME="W1" { }
  ENTRY VALUE=2 NAME="W2" { }
  ENTRY VALUE=3 NAME="W3" { }
  ENTRY VALUE=4 NAME="W4" { }
  ENTRY VALUE=5 NAME="W5" { }
  ENTRY VALUE=6 NAME="W6" { }
  ENTRY VALUE=7 NAME="W7" { }
  ENTRY VALUE=8 NAME="W8" { }
  ENTRY VALUE=9 NAME="W9" { }
  ENTRY VALUE=10 NAME="W10" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="LP_ABLUFT" FIXED=F
 user="RPOLLINGE1" time=1478248990/* "04-Nov-2016 09:43:10" */
{
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="kein Abluftsystem" { }
  ENTRY VALUE=10 NAME="P1630" { }
  ENTRY VALUE=20 NAME="P1660" { }
  ENTRY VALUE=30 NAME="S511" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_FUEHR_REGLER" FIXED=F
 user="ADMINISTRATOR" time=1247140913/* "09-Jul-2009 14:01:53" */
{
  DESCRIPTION="Fuehrungs Regler fuer Transfer Auswahl"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="kein Regler" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_GASSTATION" FIXED=F
 user="ADMINISTRATOR" time=1247140913/* "09-Jul-2009 14:01:53" */
{
  DESCRIPTION="Gasstationen"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="keine" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_PUMPE" FIXED=F
 user="RPOLLINGE1" time=1455784516/* "18-Feb-2016 09:35:16" */
{
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="keine Pumpe" { }
  ENTRY VALUE=1 NAME="P117" { }
  ENTRY VALUE=2 NAME="P122" { }
  ENTRY VALUE=4 NAME="P124" { }
  ENTRY VALUE=6 NAME="P126" { }
  ENTRY VALUE=8 NAME="P1421" { }
  ENTRY VALUE=10 NAME="P1058" { }
  ENTRY VALUE=14 NAME="P1098" { }
  ENTRY VALUE=15 NAME="Q2703" { }
  ENTRY VALUE=20 NAME="Q2013" { }
  ENTRY VALUE=23 NAME="Q2113" { }
  ENTRY VALUE=25 NAME="Q2203" { }
  ENTRY VALUE=30 NAME="Q2303" { }
  ENTRY VALUE=32 NAME="Q2403" { }
  ENTRY VALUE=35 NAME="R2903" { }
  ENTRY VALUE=40 NAME="Q2813" { }
  ENTRY VALUE=45 NAME="S5203" { }
  ENTRY VALUE=50 NAME="S5085" { }
  ENTRY VALUE=55 NAME="S532" { }
  ENTRY VALUE=56 NAME="S533" { }
  ENTRY VALUE=60 NAME="S5071" { }
  ENTRY VALUE=70 NAME="Z212" { }
  ENTRY VALUE=75 NAME="Z4021" { }
  ENTRY VALUE=80 NAME="Z4031" { }
  ENTRY VALUE=85 NAME="Z4081" { }
  ENTRY VALUE=90 NAME="Z4106" { }
  ENTRY VALUE=91 NAME="Q2571" { }
  ENTRY VALUE=92 NAME="Q2451" { }
  ENTRY VALUE=93 NAME="Q3051" { }
  ENTRY VALUE=95 NAME="Z4411" { }
  ENTRY VALUE=100 NAME="X1010" { }
  ENTRY VALUE=101 NAME="X1110" { }
  ENTRY VALUE=102 NAME="X1210" { }
  ENTRY VALUE=110 NAME="I1311" { }
  ENTRY VALUE=111 NAME="I1321" { }
  ENTRY VALUE=112 NAME="I1331" { }
  ENTRY VALUE=113 NAME="I1341" { }
  ENTRY VALUE=120 NAME="Z1261" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_UNITS" FIXED=F
 user="RPOLLINGE1" time=1492070171/* "13-Apr-2017 09:56:11" */
{
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="no UNIT" { }
  ENTRY VALUE=1 NAME="L_RW" { }
  ENTRY VALUE=2 NAME="Q2600" { }
  ENTRY VALUE=3 NAME="Q2300" { }
  ENTRY VALUE=4 NAME="Q2000" { }
  ENTRY VALUE=5 NAME="Q2200" { }
  ENTRY VALUE=6 NAME="S508" { }
  ENTRY VALUE=7 NAME="Q2700" { }
  ENTRY VALUE=8 NAME="Z4000" { }
  ENTRY VALUE=9 NAME="Z4030" { }
  ENTRY VALUE=10 NAME="Z4040" { }
  ENTRY VALUE=11 NAME="Z4080" { }
  ENTRY VALUE=12 NAME="Q2030" { }
  ENTRY VALUE=13 NAME="Q2070" { }
  ENTRY VALUE=14 NAME="Q2020" { }
  ENTRY VALUE=15 NAME="Q3000" { }
  ENTRY VALUE=16 NAME="Q3100" { }
  ENTRY VALUE=17 NAME="Q3050" { }
  ENTRY VALUE=18 NAME="Q2570" { }
  ENTRY VALUE=19 NAME="Q2580" { }
  ENTRY VALUE=20 NAME="Q2900" { }
  ENTRY VALUE=21 NAME="P101" { }
  ENTRY VALUE=22 NAME="P102" { }
  ENTRY VALUE=23 NAME="Q2100" { }
  ENTRY VALUE=24 NAME="Q2800" { }
  ENTRY VALUE=25 NAME="P105" { }
  ENTRY VALUE=26 NAME="P109" { }
  ENTRY VALUE=27 NAME="I7010" { }
  ENTRY VALUE=28 NAME="Z154" { }
  ENTRY VALUE=29 NAME="P5400" { }
  ENTRY VALUE=30 NAME="P5500" { }
  ENTRY VALUE=31 NAME="P116" { }
  ENTRY VALUE=32 NAME="P118" { }
  ENTRY VALUE=33 NAME="P121" { }
  ENTRY VALUE=34 NAME="P123" { }
  ENTRY VALUE=35 NAME="R2900" { }
  ENTRY VALUE=36 NAME="S5200" { }
  ENTRY VALUE=37 NAME="S501" { }
  ENTRY VALUE=38 NAME="S502" { }
  ENTRY VALUE=39 NAME="S5070" { }
  ENTRY VALUE=40 NAME="P1400" { }
  ENTRY VALUE=41 NAME="P1410" { }
  ENTRY VALUE=42 NAME="P3000" { }
  ENTRY VALUE=43 NAME="P3100" { }
  ENTRY VALUE=44 NAME="Q2450" { }
  ENTRY VALUE=45 NAME="Q2500" { }
  ENTRY VALUE=46 NAME="Q2400" { }
  ENTRY VALUE=47 NAME="I7500" { }
  ENTRY VALUE=48 NAME="P1420" { }
  ENTRY VALUE=49 NAME="P125" { }
  ENTRY VALUE=50 NAME="Q2560" { }
  ENTRY VALUE=55 NAME="S506" { }
  ENTRY VALUE=58 NAME="S511" { }
  ENTRY VALUE=60 NAME="Z6000" { }
  ENTRY VALUE=61 NAME="V6000" { }
  ENTRY VALUE=62 NAME="T6000" { }
  ENTRY VALUE=70 NAME="Z4100" { }
  ENTRY VALUE=72 NAME="Z4300" { }
  ENTRY VALUE=73 NAME="Z4400" { }
  ENTRY VALUE=101 NAME="R2950" { }
  ENTRY VALUE=102 NAME="R2960" { }
  ENTRY VALUE=103 NAME="Z1110" { }
  ENTRY VALUE=104 NAME="Z1120" { }
  ENTRY VALUE=105 NAME="Z1130" { }
  ENTRY VALUE=106 NAME="Z1140" { }
  ENTRY VALUE=107 NAME="Z1150" { }
  ENTRY VALUE=108 NAME="Z1160" { }
  ENTRY VALUE=109 NAME="Z1170" { }
  ENTRY VALUE=110 NAME="Z1220" { }
  ENTRY VALUE=111 NAME="Z1230" { }
  ENTRY VALUE=112 NAME="Z1240" { }
  ENTRY VALUE=113 NAME="Z1250" { }
  ENTRY VALUE=114 NAME="Z1280" { }
  ENTRY VALUE=115 NAME="Z1650" { }
  ENTRY VALUE=116 NAME="Z2050" { }
  ENTRY VALUE=117 NAME="Z1210" { }
  ENTRY VALUE=118 NAME="Z1260" { }
  ENTRY VALUE=122 NAME="Z201" { }
  ENTRY VALUE=123 NAME="Z203" { }
  ENTRY VALUE=124 NAME="Z205" { }
  ENTRY VALUE=125 NAME="Z207" { }
  ENTRY VALUE=126 NAME="Z209" { }
  ENTRY VALUE=127 NAME="Z211" { }
  ENTRY VALUE=128 NAME="Z213" { }
  ENTRY VALUE=129 NAME="Z215" { }
  ENTRY VALUE=130 NAME="Z217" { }
  ENTRY VALUE=135 NAME="TANK5500" { }
  ENTRY VALUE=150 NAME="X1000" { }
  ENTRY VALUE=151 NAME="X1005" { }
  ENTRY VALUE=152 NAME="X1100" { }
  ENTRY VALUE=153 NAME="X1105" { }
  ENTRY VALUE=154 NAME="X1200" { }
  ENTRY VALUE=160 NAME="I1310" { }
  ENTRY VALUE=161 NAME="I1320" { }
  ENTRY VALUE=162 NAME="I1330" { }
  ENTRY VALUE=163 NAME="I1340" { }
  ENTRY VALUE=180 NAME="TRANS01" { }
  ENTRY VALUE=181 NAME="TRANS02" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_VAKUUMPUMPE" FIXED=F
 user="RPOLLINGE1" time=1488531349/* "03-Mar-2017 09:55:49" */
{
  DESCRIPTION="Vakuum System Auswahl"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="kein" { }
  ENTRY VALUE=19 NAME="Z505" { }
  ENTRY VALUE=20 NAME="Z6061" { }
  ENTRY VALUE=21 NAME="V6061" { }
  ENTRY VALUE=22 NAME="Z304" { }
  ENTRY VALUE=23 NAME="Z1650" { }
  ENTRY VALUE=24 NAME="Z4201" { }
  ENTRY VALUE=25 NAME="Z4211" { }
  ENTRY VALUE=26 NAME="Q7300" { }
  ENTRY VALUE=27 NAME="P7400" { }
  ENTRY VALUE=28 NAME="P7500" { }
  ENTRY VALUE=29 NAME="Q7200" { }
  ENTRY VALUE=30 NAME="P7600" { }
  ENTRY VALUE=31 NAME="Q7100" { }
  ENTRY VALUE=32 NAME="T6061" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LP_ZAEHLER" FIXED=F
 user="MPOKRZYWKA" time=1569998353/* "02-Oct-2019 08:39:13" */
{
  DESCRIPTION="Zahler Auswahl"
  CATEGORY="Named Sets/L_GF"
  ENTRY VALUE=0 NAME="kein Zaehler" { }
  ENTRY VALUE=1 NAME="Q2710" { }
  ENTRY VALUE=2 NAME="I1276" { }
  ENTRY VALUE=3 NAME="I1277" { }
  ENTRY VALUE=4 NAME="I1376" { }
  ENTRY VALUE=6 NAME="I1476" { }
  ENTRY VALUE=7 NAME="I1477" { }
  ENTRY VALUE=8 NAME="I1278" { }
  ENTRY VALUE=10 NAME="I1279" { }
  ENTRY VALUE=11 NAME="I1280" { }
  ENTRY VALUE=12 NAME="I1275" { }
  ENTRY VALUE=13 NAME="I1281" { }
  ENTRY VALUE=14 NAME="I1176" { }
  ENTRY VALUE=15 NAME="I1177" { }
  ENTRY VALUE=16 NAME="I1178" { }
  ENTRY VALUE=17 NAME="I1179" { }
  ENTRY VALUE=18 NAME="I1180" { }
  ENTRY VALUE=19 NAME="I1181" { }
  ENTRY VALUE=20 NAME="S508_DESTIL" { }
  ENTRY VALUE=30 NAME="R2900_DESTIL" { }
  ENTRY VALUE=40 NAME="Q2400_DESTIL" { }
  ENTRY VALUE=50 NAME="Z4300_DESTIL" { }
  ENTRY VALUE=60 NAME="Z4400_DESTIL" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LD_Produkt" FIXED=F
 user="MVENETZ2" time=1337093849/* "15-May-2012 16:57:29" */
{
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="Ausser Betrieb" { }
  ENTRY VALUE=1 NAME="Reinigung" { }
  ENTRY VALUE=2 NAME="Ungültiges Produkt" { }
  ENTRY VALUE=7 NAME="BAS670" { }
  ENTRY VALUE=8 NAME="Etodolac" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="LE_QZ" FIXED=F
 user="ADMINISTRATOR" time=1246972283/* "07-Jul-2009 15:11:23" */
{
  DESCRIPTION="Definition fuer Q- oder Z-Geraet"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="not Q- or Z-relevant" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Q-relevant" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Z-relevant" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_Count-pv" FIXED=F
 user="ADMINISTRATOR" time=1246972284/* "07-Jul-2009 15:11:24" */
{
  DESCRIPTION="Counter-States Lonza"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="Off" { }
  ENTRY VALUE=1 NAME="Running" { }
  ENTRY VALUE=2 NAME="Interrupted" { }
  ENTRY VALUE=3 NAME="Completed" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_EIN_AUS" FIXED=F
 user="ADMINISTRATOR" time=1233144227/* "28-Jan-2009 13:03:47" */
{
  DESCRIPTION="Ein Aus"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="AUS" { }
  ENTRY VALUE=1 NAME="EIN" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_FALSE_TRUE" FIXED=F
 user="ADMINISTRATOR" time=1246972307/* "07-Jul-2009 15:11:47" */
{
  DESCRIPTION="False True"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="FALSE" { }
  ENTRY VALUE=1 NAME="TRUE" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_JA_NEIN" FIXED=F
 user="ADMINISTRATOR" time=1233144227/* "28-Jan-2009 13:03:47" */
{
  DESCRIPTION="Ja Nein"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="NEIN" { }
  ENTRY VALUE=1 NAME="JA" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_PID_STRUCTURE" FIXED=F
 user="ADMINISTRATOR" time=1246972284/* "07-Jul-2009 15:11:24" */
{
  DESCRIPTION="Auswahl der Reglerstruktur für den MUSCH-Regler ""PI"" / Version 1.0 / 26-Jan-2007 Ch. Zeiter"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="P" { }
  ENTRY VALUE=1 NAME="PI" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_QZ" FIXED=F
 user="ADMINISTRATOR" time=1233144228/* "28-Jan-2009 13:03:48" */
{
  DESCRIPTION="Definition fuer Q- oder Z-Geraet"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="nicht Q- oder Z-relevant" { }
  ENTRY VALUE=1 NAME="Q-relevant" { }
  ENTRY VALUE=2 NAME="Z-relevant" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_Zaehler-pv" FIXED=F
 user="ADMINISTRATOR" time=1246972284/* "07-Jul-2009 15:11:24" */
{
  DESCRIPTION="Zähler-Stati Lonza"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="aus" { }
  ENTRY VALUE=1 NAME="läuft" { }
  ENTRY VALUE=2 NAME="unterbrochen" { }
  ENTRY VALUE=3 NAME="beendet" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_mtr2-pv" FIXED=T
 user="ADMINISTRATOR" time=1246972301/* "07-Jul-2009 15:11:41" */
{
  DESCRIPTION="Motor-Stati Lonza "
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="steht" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="läuft" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="NICHT DEFINIERT" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_states_mtr2" FIXED=T
 user="ADMINISTRATOR" time=1246972303/* "07-Jul-2009 15:11:43" */
{
  DESCRIPTION="Motor-Stati Lonza"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="steht" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="läuft" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="stoppt" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="startet" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="not used 2" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Fehler stoppen" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Fehler starten" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="not used 3" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Interlock" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_states_vlvnc" FIXED=F
 user="ADMINISTRATOR" time=1246972305/* "07-Jul-2009 15:11:45" */
{
  DESCRIPTION="Ventil-Stati Lonza"
  CATEGORY="Named Sets/L_GFE"
  ENTRY VALUE=0 NAME="geschlossen" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="offen" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="schliesst" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="oeffnet" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="not used 2" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Fehler Zu" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Fehler Auf" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="not used 3" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_IO_OPTS" FIXED=F
 user="ADMINISTRATOR" time=1246972307/* "07-Jul-2009 15:11:47" */
{
  DESCRIPTION="Lonza referenzierte IO: Definition IO_OPTS / Version 1.0 / 29-Novemberl-2007 Ch. Zeiter"
  CATEGORY="Named Sets/L_IO"
  ENTRY VALUE=0 NAME="not invert" { }
  ENTRY VALUE=1 NAME="invert" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_REF_TYPE" FIXED=F
 user="ADMINISTRATOR" time=1276513445/* "14-Jun-2010 13:04:05" */
{
  DESCRIPTION="Lonza referenzierte IO: Reference Type / Version 2.0 / 10-Mai-2010 Ch. Zeiter"
  CATEGORY="Named Sets/L_IO"
  ENTRY VALUE=0 NAME="L_RS232" { }
  ENTRY VALUE=1 NAME="L_PROFIBUS" { }
  ENTRY VALUE=2 NAME="L_WAGO" { }
  ENTRY VALUE=3 NAME="L_SIS" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="L_TYPE" FIXED=F
 user="ADMINISTRATOR" time=1246972308/* "07-Jul-2009 15:11:48" */
{
  DESCRIPTION="Lonza referenzierte IO: Linearization Type / Version 1.0 / 29-November-2007 Ch. Zeiter"
  CATEGORY="Named Sets/L_IO"
  ENTRY VALUE=0 NAME="Indirect" { }
  ENTRY VALUE=1 NAME="Direct" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$boolean_error" FIXED=T
 user="hawkbuild" time=1114057927/* "21-Apr-2005 06:32:07" */
{
  DESCRIPTION="Boolean Error Select"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="False" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="True" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="UseLast" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_cem_overrides" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Cause Effect Matrix block overrides"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="None" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="All Associated Causes Masked" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Forced To Normal" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Forced to Trip" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_cem_states" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Cause Effect Matrix block Effect states"
  CATEGORY="Named Sets"
  ENTRY VALUE=1 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Waiting for Reset Permit" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Ready to Reset" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Waiting for Start Permit" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Normal" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Trip Initiated - Delayed" { SELECTABLE=F }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="$ctlr_force_effect" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Cause Effect Matrix block Effect force states"
  CATEGORY="Named Sets"
  ENTRY VALUE=1 NAME="Do Not Force" { }
  ENTRY VALUE=2 NAME="Force Trip" { }
  ENTRY VALUE=3 NAME="Force Normal" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="$ctlr_report_opts" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Reporting options"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Alarm conditions do not roll up to module level" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_std_overrides" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="State Transition block overrides"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="None" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="All associated transitions masked" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="State forced" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_std_seq_states" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Default states for State Transition and Sequencer blocks"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Disabled" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Description State 1" { }
  ENTRY VALUE=2 NAME="Description State 2" { }
  ENTRY VALUE=3 NAME="Description State 3" { }
  ENTRY VALUE=4 NAME="Description State 4" { }
  ENTRY VALUE=5 NAME="Description State 5" { }
  ENTRY VALUE=6 NAME="Description State 6" { }
  ENTRY VALUE=7 NAME="Description State 7" { }
  ENTRY VALUE=8 NAME="Description State 8" { }
  ENTRY VALUE=9 NAME="Description State 9" { }
  ENTRY VALUE=10 NAME="Description State 10" { }
  ENTRY VALUE=11 NAME="Description State 11" { }
  ENTRY VALUE=12 NAME="Description State 12" { }
  ENTRY VALUE=13 NAME="Description State 13" { }
  ENTRY VALUE=14 NAME="Description State 14" { }
  ENTRY VALUE=15 NAME="Description State 15" { }
  ENTRY VALUE=16 NAME="Description State 16" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_votr_pretrip_status" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Analog Voter block pre-trip status states"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Normal" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Pre-Tripped" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Pre-Trip Inhibited" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Voted to Pre-Trip - Delayed" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Voted Normal - Delayed" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$ctlr_votr_trip_status" FIXED=T
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Trip status states for Voter blocks"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Normal" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Trip Inhibited" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Voted to Trip - Delayed" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Voted Normal - Delayed" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$dc_default" FIXED=T
 user="hawkbuild" time=984800937/* "17-Mar-2001 04:48:57" */
{
  DESCRIPTION="Default Command/Confirm state names for the Device Control function block"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Passive" { }
  ENTRY VALUE=1 NAME="Active 1" { }
  ENTRY VALUE=2 NAME="Active 2" { }
  ENTRY VALUE=255 NAME="Undefined" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$dc_fail" FIXED=T
 user="hawkbuild" time=984800949/* "17-Mar-2001 04:49:09" */
{
  DESCRIPTION="Default failure condition names for the Device Control function block"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Passive Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Active 1 confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Active 2 confirm time" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Passive confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Active 1 confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Active 2 confirm lost" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$dc_states" FIXED=T
 user="hawkbuild" time=984800947/* "17-Mar-2001 04:49:07" */
{
  DESCRIPTION="Default device state names for the Device Control function block"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Passive" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Active 1" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Confirmed Active 2" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Going to Passive" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Going to Active 1" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Going to Active 2" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Failed Passive" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed Active 1" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Failed Active 2" { SELECTABLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$enable" FIXED=T
 user="hawkbuild" time=1114057927/* "21-Apr-2005 06:32:07" */
{
  DESCRIPTION="TOD Enable"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Disabled" { }
  ENTRY VALUE=1 NAME="Enabled" { }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="$module_states" FIXED=T
 user="hawkbuild" time=984800958/* "17-Mar-2001 04:49:18" */
{
  DESCRIPTION="Command/Feedback state names for Control Modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="In Service" { }
  ENTRY VALUE=1 NAME="Out Of Service" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$phase_command" FIXED=T
 user="hawkbuild" time=984800955/* "17-Mar-2001 04:49:15" */
{
  DESCRIPTION="Commands for the Phase Logic Module"
  CATEGORY="Named Sets"
  ENTRY VALUE=10 NAME="Abort" { }
  ENTRY VALUE=20 NAME="Hold" { }
  ENTRY VALUE=30 NAME="Stop" { }
  ENTRY VALUE=40 NAME="Reset" { }
  ENTRY VALUE=50 NAME="Pause" { }
  ENTRY VALUE=60 NAME="SingleStep" { }
  ENTRY VALUE=70 NAME="Download" { }
  ENTRY VALUE=80 NAME="Resume" { }
  ENTRY VALUE=90 NAME="Restart" { }
  ENTRY VALUE=100 NAME="Start" { }
  ENTRY VALUE=110 NAME="Automatic" { }
  ENTRY VALUE=120 NAME="Manual" { }
  ENTRY VALUE=130 NAME="Clear Failures" { }
  DEFAULT_VALUE=100
}
ENUMERATION_SET NAME="$phase_owner_id" FIXED=T
 user="hawkbuild" time=984800955/* "17-Mar-2001 04:49:15" */
{
  DESCRIPTION="Indicates the owner of the Phase Logic Module"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="DeltaV Batch" { }
  ENTRY VALUE=1 NAME="External" { }
  ENTRY VALUE=254 NAME="Not Loaded" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$phase_restart_types" FIXED=T
 user="hawkbuild" time=984800961/* "17-Mar-2001 04:49:21" */
{
  DESCRIPTION="Restart type for Phase Logic Modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Continue" { }
  ENTRY VALUE=1 NAME="From Start" { }
  ENTRY VALUE=2 NAME="From Start Without Download" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$phase_state" FIXED=T
 user="hawkbuild" time=984800955/* "17-Mar-2001 04:49:15" */
{
  DESCRIPTION="States of the Phase Logic Module"
  CATEGORY="Named Sets"
  ENTRY VALUE=10 NAME="Aborting" { SELECTABLE=F }
  ENTRY VALUE=20 NAME="Holding" { SELECTABLE=F }
  ENTRY VALUE=30 NAME="Stopping" { SELECTABLE=F }
  ENTRY VALUE=40 NAME="Restarting" { SELECTABLE=F }
  ENTRY VALUE=50 NAME="Running" { SELECTABLE=F }
  ENTRY VALUE=60 NAME="Held" { SELECTABLE=F }
  ENTRY VALUE=70 NAME="Complete" { SELECTABLE=F }
  ENTRY VALUE=80 NAME="Stopped" { SELECTABLE=F }
  ENTRY VALUE=90 NAME="Aborted" { SELECTABLE=F }
  ENTRY VALUE=100 NAME="Idle" { SELECTABLE=F }
  ENTRY VALUE=110 NAME="Starting" { SELECTABLE=F }
  ENTRY VALUE=120 NAME="Ready" { SELECTABLE=F }
  ENTRY VALUE=254 NAME="Not Loaded" { SELECTABLE=F }
  DEFAULT_VALUE=100
}
ENUMERATION_SET NAME="$phase_wdog_states" FIXED=T
 user="hawkbuild" time=984800959/* "17-Mar-2001 04:49:19" */
{
  DESCRIPTION="Phase Watchdog States"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OK" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="SUSPECT" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="FAILED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$recipe_state" FIXED=T
 user="hawkbuild" time=984800961/* "17-Mar-2001 04:49:21" */
{
  DESCRIPTION="States of a Recipe Element"
  CATEGORY="Named Sets"
  ENTRY VALUE=10 NAME="Aborting" { SELECTABLE=F }
  ENTRY VALUE=20 NAME="Holding" { SELECTABLE=F }
  ENTRY VALUE=30 NAME="Stopping" { SELECTABLE=F }
  ENTRY VALUE=40 NAME="Restarting" { SELECTABLE=F }
  ENTRY VALUE=50 NAME="Running" { SELECTABLE=F }
  ENTRY VALUE=60 NAME="Held" { SELECTABLE=F }
  ENTRY VALUE=70 NAME="Complete" { SELECTABLE=F }
  ENTRY VALUE=80 NAME="Stopped" { SELECTABLE=F }
  ENTRY VALUE=90 NAME="Aborted" { SELECTABLE=F }
  ENTRY VALUE=100 NAME="Idle" { SELECTABLE=F }
  DEFAULT_VALUE=100
}
ENUMERATION_SET NAME="$sfc_action_states" FIXED=T
 user="hawkbuild" time=984800959/* "17-Mar-2001 04:49:19" */
{
  DESCRIPTION="SFC Action States"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Inactive" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Delayed" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Active" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Complete" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Failed" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Pending" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$sfc_commands" FIXED=T
 user="hawkbuild" time=984800954/* "17-Mar-2001 04:49:14" */
{
  DESCRIPTION="Command state names for Sequential Function Charts"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Start Sequence" { }
  ENTRY VALUE=1 NAME="Stop Sequence" { }
  ENTRY VALUE=5 NAME="Reset Sequence" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$sfc_initial_states" FIXED=T
 user="hawkbuild" time=984800954/* "17-Mar-2001 04:49:14" */
{
  DESCRIPTION="Initial state names for Sequential Function Charts"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Sequence Idle" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Sequence Active" { SELECTABLE=F }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="$sfc_states" FIXED=T
 user="hawkbuild" time=984800955/* "17-Mar-2001 04:49:15" */
{
  DESCRIPTION="Feedback state names for Sequential Function Charts"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Sequence Idle" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Sequence Active" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Sequence Stopped" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Sequence Completed" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Sequence Blocked" { SELECTABLE=F }
  DEFAULT_VALUE=1
}
ENUMERATION_SET NAME="$state" FIXED=T
 user="hawkbuild" time=1114057927/* "21-Apr-2005 06:32:07" */
{
  DESCRIPTION="TOD State"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Idle" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Armed" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Terminal" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$sysstat_opts" FIXED=T
 user="hawkbuild" time=1114057927/* "21-Apr-2005 06:32:07" */
{
  DESCRIPTION="sysstat options"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Switchover" { }
  ENTRY VALUE=1 NAME="AnyDownload" { }
  ENTRY VALUE=2 NAME="MyDownload" { }
  ENTRY VALUE=3 NAME="Powerfail" { }
  ENTRY VALUE=4 NAME="TotalDownload" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="$time_format" FIXED=T
 user="hawkbuild" time=1114057927/* "21-Apr-2005 06:32:07" */
{
  DESCRIPTION="Time Format"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Local" { }
  ENTRY VALUE=1 NAME="UTC" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="equipment_availability" FIXED=F
 user="hawkbuild" time=1229075064/* "12-Dec-2008 10:44:24" */
{
  DESCRIPTION="Equipment Availability States of the Unit Module"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OK" { }
  ENTRY VALUE=255 NAME="Not Available" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="fail_mtr2" FIXED=T
 user="hawkbuild" time=984800949/* "17-Mar-2001 04:49:09" */
{
  DESCRIPTION="Failure condition names for two-state motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="STOP Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="START confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=4 NAME="STOPPED confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="RUNNING confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="fail_mtrfr" FIXED=T
 user="hawkbuild" time=984800949/* "17-Mar-2001 04:49:09" */
{
  DESCRIPTION="Failure condition names for forward/reverse motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="STOP Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="FORWARD confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="REVERSE confirm time" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="STOPPED confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="FORWARD confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="REVERSE confirm lost" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="fail_mtrfs" FIXED=T
 user="hawkbuild" time=984800950/* "17-Mar-2001 04:49:10" */
{
  DESCRIPTION="Failure condition names for fast/slow motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="STOP Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="FAST confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="SLOW confirm time" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="STOPPED confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="FAST confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="SLOW confirm lost" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="fail_vlvnc" FIXED=T
 user="hawkbuild" time=984800952/* "17-Mar-2001 04:49:12" */
{
  DESCRIPTION="Failure condition names for normally closed valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="CLOSE Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="OPEN confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=4 NAME="CLOSED confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="OPEN confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="fail_vlvno" FIXED=T
 user="hawkbuild" time=984800952/* "17-Mar-2001 04:49:12" */
{
  DESCRIPTION="Failure condition names for normally open valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Clear" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="OPEN Confirm time" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="CLOSE confirm time" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=4 NAME="OPEN confirm lost" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="CLOSED confirm lost" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=7 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="mtr2" FIXED=T
 user="hawkbuild" time=984800940/* "17-Mar-2001 04:49:00" */
{
  DESCRIPTION="Command/Confirm state names for two-state motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="STOP" { }
  ENTRY VALUE=1 NAME="START" { }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="mtr2-pv" FIXED=T
 user="hawkbuild" time=984800941/* "17-Mar-2001 04:49:01" */
{
  DESCRIPTION="Confirm state names for two-state motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="STOPPED" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="RUNNING" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="mtr2-sp" FIXED=T
 user="hawkbuild" time=984800940/* "17-Mar-2001 04:49:00" */
{
  DESCRIPTION="Command state names for two-state motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="STOP" { }
  ENTRY VALUE=1 NAME="START" { }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="mtrfr" FIXED=T
 user="hawkbuild" time=984800941/* "17-Mar-2001 04:49:01" */
{
  DESCRIPTION="Command/Confirm state names for forward/reverse motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="STOP" { }
  ENTRY VALUE=1 NAME="FORWARD" { }
  ENTRY VALUE=2 NAME="REVERSE" { }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="mtrfs" FIXED=T
 user="hawkbuild" time=984800941/* "17-Mar-2001 04:49:01" */
{
  DESCRIPTION="Command/Confirm state names for fast/slow motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="STOP" { }
  ENTRY VALUE=1 NAME="FAST" { }
  ENTRY VALUE=2 NAME="SLOW" { }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="phase_boolean" FIXED=T
 user="hawkbuild" time=984800960/* "17-Mar-2001 04:49:20" */
{
  DESCRIPTION="Phase Boolean"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="NO" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="YES" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="phase_failures" FIXED=F
 user="ADMINISTRATOR" time=1525165500/* "01-May-2018 11:05:00" */
{
  DESCRIPTION="Failure States of the Phase Logic Module, Version 1.0"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OK" { }
  ENTRY VALUE=1 NAME="PLM Watchdog Failed" { }
  ENTRY VALUE=2 NAME="Write To REQUEST Attribute Failed" { }
  ENTRY VALUE=3 NAME="Controller Switchover Detected" { }
  ENTRY VALUE=100 NAME="GF FAILED" { }
  ENTRY VALUE=101 NAME="ACTION COMPLETE FAILED" { }
  ENTRY VALUE=255 NAME="FAILED" { }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="states_mtr2" FIXED=T
 user="hawkbuild" time=984800947/* "17-Mar-2001 04:49:07" */
{
  DESCRIPTION="Device state names for two-state motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Stopped" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Running" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=3 NAME="Stopping" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Starting" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=6 NAME="Failed STOP" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed START" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="not used 3" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="states_mtrfr" FIXED=T
 user="hawkbuild" time=984800947/* "17-Mar-2001 04:49:07" */
{
  DESCRIPTION="Device state names for forward/reverse motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Stopped" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Forward" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Confirmed Reverse" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Stopping" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Going to Forward" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Going to Reverse" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Failed STOP" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed FORWARD" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Failed REVERSE" { SELECTABLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="states_mtrfs" FIXED=T
 user="hawkbuild" time=984800948/* "17-Mar-2001 04:49:08" */
{
  DESCRIPTION="Device state names for fast/slow motor modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Stopped" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Fast" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="Confirmed Slow" { SELECTABLE=F }
  ENTRY VALUE=3 NAME="Stopping" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Going to Fast" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="Going to Slow" { SELECTABLE=F }
  ENTRY VALUE=6 NAME="Failed STOP" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed FAST" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="Failed SLOW" { SELECTABLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="states_vlvnc" FIXED=T
 user="hawkbuild" time=984800948/* "17-Mar-2001 04:49:08" */
{
  DESCRIPTION="Device state names for normally closed valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Closed" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Open" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=3 NAME="Closing" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Opening" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=6 NAME="Failed CLOSE" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed OPEN" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="not used 3" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="states_vlvno" FIXED=T
 user="hawkbuild" time=984800948/* "17-Mar-2001 04:49:08" */
{
  DESCRIPTION="Device state names for normally open valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="Confirmed Open" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="Confirmed Closed" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=3 NAME="Opening" { SELECTABLE=F }
  ENTRY VALUE=4 NAME="Closing" { SELECTABLE=F }
  ENTRY VALUE=5 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=6 NAME="Failed OPEN" { SELECTABLE=F }
  ENTRY VALUE=7 NAME="Failed CLOSE" { SELECTABLE=F }
  ENTRY VALUE=8 NAME="not used 3" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=9 NAME="Tripped" { SELECTABLE=F }
  ENTRY VALUE=10 NAME="Shutdown/Interlocked" { SELECTABLE=F }
  ENTRY VALUE=11 NAME="Locked" { SELECTABLE=F }
  ENTRY VALUE=255 NAME="No valid state" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="test" FIXED=F
 user="KIMHOF1" time=1256911402/* "30-Oct-2009 15:03:22" */
{
  DESCRIPTION="test"
  CATEGORY="Named Sets"
  ENTRY VALUE=4 NAME="4_kerzen" { }
  ENTRY VALUE=5 NAME="5_Kerzen" { }
  DEFAULT_VALUE=4
}
ENUMERATION_SET NAME="vlv3" FIXED=T
 user="hawkbuild" time=984800946/* "17-Mar-2001 04:49:06" */
{
  DESCRIPTION="Command/Confirm state names for three-way valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="CLOSE" { }
  ENTRY VALUE=1 NAME="OUTLET1" { }
  ENTRY VALUE=2 NAME="OUTLET2" { }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvnc" FIXED=T
 user="hawkbuild" time=984800942/* "17-Mar-2001 04:49:02" */
{
  DESCRIPTION="Command/Confirm state names for normally closed valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="CLOSE" { }
  ENTRY VALUE=1 NAME="OPEN" { }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvnc-pv" FIXED=T
 user="hawkbuild" time=984800943/* "17-Mar-2001 04:49:03" */
{
  DESCRIPTION="Confirm state names for normally closed valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="CLOSED" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="OPEN" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvnc-sp" FIXED=T
 user="hawkbuild" time=984800942/* "17-Mar-2001 04:49:02" */
{
  DESCRIPTION="Command state names for normally closed valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="CLOSE" { }
  ENTRY VALUE=1 NAME="OPEN" { }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvno" FIXED=T
 user="hawkbuild" time=984800942/* "17-Mar-2001 04:49:02" */
{
  DESCRIPTION="Command/Confirm state names for normally open valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OPEN" { }
  ENTRY VALUE=1 NAME="CLOSE" { }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvno-pv" FIXED=T
 user="hawkbuild" time=984800943/* "17-Mar-2001 04:49:03" */
{
  DESCRIPTION="Confirm state names for normally open valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OPEN" { SELECTABLE=F }
  ENTRY VALUE=1 NAME="CLOSED" { SELECTABLE=F }
  ENTRY VALUE=2 NAME="not used" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="UNDEFINED" { SELECTABLE=F }
  DEFAULT_VALUE=0
}
ENUMERATION_SET NAME="vlvno-sp" FIXED=T
 user="hawkbuild" time=984800943/* "17-Mar-2001 04:49:03" */
{
  DESCRIPTION="Command state names for normally open valve modules"
  CATEGORY="Named Sets"
  ENTRY VALUE=0 NAME="OPEN" { }
  ENTRY VALUE=1 NAME="CLOSE" { }
  ENTRY VALUE=2 NAME="not used 1" { SELECTABLE=F VISIBLE=F }
  ENTRY VALUE=255 NAME="not used 2" { SELECTABLE=F VISIBLE=F }
  DEFAULT_VALUE=0
}`