
export default = `/* Version: 10.3.1.3657.xr */
/* "05-Aug-2020 09:24:47" */

SCHEMA
 user="FLAMBRIGGE" time=1596611920/* "05-Aug-2020 09:18:40" */
{
  VERSION=1253152407/* "17-Sep-2009 03:53:27" */
  MAJOR_VERSION=10
  MINOR_VERSION=3
  MAINTENANCE_VERSION=1
  BUILD_VERSION=3664
  BUILD_ID="xr"
  VERSION_STR="10.3.1.3664.xr"
  ONLINE_UPGRADE=F
}
LOCALE
 user="FLAMBRIGGE" time=1596611920/* "05-Aug-2020 09:18:40" */
{
  LOCALE="English_United States.1252"
}
BATCH_RECIPE NAME="OP_DRUCK" TYPE=OPERATION CATEGORY="Recipes/Operations"
 user="ADMINISTRATOR" time=1525166552/* "01-May-2018 11:22:32" */
{
  DESCRIPTION="Druck"
  USE_EQUIPMENT_TRAINS=F
  EQUIPMENT_UNIT_CLASS="B"
  AUTHOR="Hutter Fredy"
  ABSTRACT=""
  BATCH_UNITS=""
  BATCH_LENGTH=""
  DEFAULT_BATCH_SIZE=100
  MINIMUM_BATCH_SIZE=1
  MAXIMUM_BATCH_SIZE=100
  PRODUCT_CODE=""
  PRODUCT_NAME="Alle Produkte"
  RECIPE_APPROVAL_INFO="Hutter Fredy"
  VERSION="1.0"
  FORMULA_PARAMETER NAME="FP_FSB_PSH" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_FSB_PSL" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_OPTION" TYPE=ENUMERATION_VALUE
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PAH" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PAHH" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PAL" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PALL" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PC_W" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_PV_KENNLINIE" TYPE=ENUMERATION_VALUE
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_RAMPE" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  FORMULA_PARAMETER NAME="FP_BESCHREI_TEXT" TYPE=UNICODE_STRING
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
  }
  FORMULA_PARAMETER NAME="FP_PC_W_HO" TYPE=BATCH_PARAMETER_REAL
  {
    CONNECTION=INPUT
    RECTANGLE= { X=-50 Y=-50 H=1 W=1 }
    GROUP="Operating"
  }
  ATTRIBUTE_INSTANCE NAME="FP_FSB_PSH"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=150 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_FSB_PSL"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=-150 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_OPTION"
  {
    VALUE
    {
      SET="LGF_DRUCK_OPT"
      STRING_VALUE="ABLUFT1_REGLER"
      CHANGEABLE=F
    }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PAH"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=1150 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PAHH"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=1200 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PAL"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=-200 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PALL"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=-300 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PC_W"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=50 UNITS="mbar" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PV_KENNLINIE"
  {
    VALUE
    {
      SET="L_EIN_AUS"
      STRING_VALUE="AUS"
      CHANGEABLE=F
    }
  }
  ATTRIBUTE_INSTANCE NAME="FP_RAMPE"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=0 SCALABLE=F CV=100 UNITS="            " }
  }
  ATTRIBUTE_INSTANCE NAME="FP_BESCHREI_TEXT"
  {
    VALUE { CV="" }
  }
  ATTRIBUTE_INSTANCE NAME="FP_PC_W_HO"
  {
    VALUE { DESCRIPTION="" HIGH=20000 LOW=-1000 SCALABLE=F CV=50 UNITS="mbar" }
  }
  PFC_ALGORITHM
  {
    STEP NAME="DRUCK:1" DEFINITION="DRUCK"
    {
      DESCRIPTION=""
      RECTANGLE= { X=50 Y=130 H=40 W=100 }
      STEP_PARAMETER NAME="FP_BESCHREI_TEXT"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_BESCHREI_TEXT"
      }
      STEP_PARAMETER NAME="FP_FSB_PSH"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_FSB_PSH"
      }
      STEP_PARAMETER NAME="FP_FSB_PSL"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_FSB_PSL"
      }
      STEP_PARAMETER NAME="FP_OPTION"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_OPTION"
      }
      STEP_PARAMETER NAME="FP_PAH"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PAH"
      }
      STEP_PARAMETER NAME="FP_PAHH"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PAHH"
      }
      STEP_PARAMETER NAME="FP_PAL"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PAL"
      }
      STEP_PARAMETER NAME="FP_PALL"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PALL"
      }
      STEP_PARAMETER NAME="FP_PC_W"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PC_W"
      }
      STEP_PARAMETER NAME="FP_PC_W_HO"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PC_W_HO"
      }
      STEP_PARAMETER NAME="FP_PV_KENNLINIE"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_PV_KENNLINIE"
      }
      STEP_PARAMETER NAME="FP_RAMPE"
      {
        ORIGIN=DEFERRED
        DEFERRED_TO="FP_RAMPE"
      }
      STEP_PARAMETER NAME="RP_FSB_WART_ZEIT"
      {
        ORIGIN=CONSTANT
      }
      KEY_PARAMETER=""
    }
    STEP NAME="START" DEFINITION=""
    {
      DESCRIPTION=""
      RECTANGLE= { X=50 Y=50 H=40 W=100 }
      KEY_PARAMETER=""
    }
    INITIAL_STEP="START"
    TRANSITION NAME="T1"
    {
      POSITION= { X=90 Y=100 }
      TERMINATION=F
      EXPRESSION="TRUE"
    }
    TRANSITION NAME="T2"
    {
      POSITION= { X=90 Y=180 }
      TERMINATION=T
      EXPRESSION="'DRUCK:1/BSTATUS' = '$phase_state:Complete'"
    }
    STEP_TRANSITION_CONNECTION STEP="DRUCK:1" TRANSITION="T2" { }
    STEP_TRANSITION_CONNECTION STEP="START" TRANSITION="T1" { }
    TRANSITION_STEP_CONNECTION TRANSITION="T1" STEP="DRUCK:1" { }
  }
}`